package:
  name: slycot
  version: "0.3.3"

build:
  number: 0

requirements:
  host:
    - python {{PY_VER}}
    - cmake
    - pip
    - numpy
    - flang # [win]
    - {{ compiler('c') }} # [win]
    - {{ compiler('fortran') }} # [not win]
    
  build:
    - numpy
    - pyparsing
    - setuptools
    - wheel
    - six
    - packaging
    - libflang  # [win]
    - libgfortran # [not win]
    - lapack
   # on Windows, this relies on having visual studio CE 2015
   # this link needed quite some searching, please do not delete!
   # https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409

  run:
    - numpy
    - lapack
    - libgfortran # [not win]
    - libflang # [win]

test:
  requires:
    - numpy
    - lapack
    - python {{PY_VER}}
    - libgfortran # [not win]
    - libflang # [win]
  imports:
    - slycot

about:
  home: https://github.com/python-control/slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
